version: '3.1'
services:
  web:
    container_name: web
    image: php:apache
    depends_on:
      - api
    ports:
      - "8008:80"
    volumes:
      - "${PWD}/website:/var/www/html"
    env_file:
      - .env
    networks:
      - pozos_network

  api:
    container_name: api
    image: webapi:v1.3
    build: /simple_api
    volumes:
      - "${PWD}/simple_api/student_age.json:/data/student_age.json"
    networks:
      - pozos_network

networks:
  pozos_network:
    name: pozos_network
